// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jtzxtzmrxdxydgcubmkw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp0enh0em1yeGR4eWRnY3VibWt3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzNTU3MjYsImV4cCI6MjA2NTkzMTcyNn0.KjBrJ8d7pKiO5tmohNZM195BB0_uOOFn6VTE2QJYqLM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);